name: Js

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install npm dependencies
      run: npm i --include=dev
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Static Tests (TS ESM)
      run: npm run ts-test-static
    - name: Static Tests (JS CJS)
      run: npm run static-test
    - name: Live Tests (TS ESM)
      run: npm run ts-test-live
    - name: CJS test
      run: npm run test-cjs